/* ============================================================================
 * Board Meeting — the clue bank
 * ----------------------------------------------------------------------------
 * A Jeopardy-style CostBot board. FOUR categories are drawn onto the board each
 * game; each fills FOUR value tiers ($400 / $800 / $1200 / $1600). Every tier
 * holds several clues and the game picks one at random, so the same tile is a
 * different question next time — that is the replay variety.
 *
 * Shape (mirrors shared/arcade-trivia.js):
 *   category = { id, name, icon, tiers: [ t400, t800, t1200, t1600 ] }
 *   tier     = [ clue, clue, … ]        // difficulty rises with the tier
 *   clue     = { q, c: [choices], a: <index of the correct choice>, why }
 *
 * DISNEY SONGS is "finish the TITLE" + song trivia on purpose: song titles are
 * not copyrightable, actual lyrics are — so nothing here reproduces a lyric.
 *
 * Real FinOps sits next to Disney and Movies on purpose — the mix is what makes
 * it a party game the whole team plays, not a compliance quiz.
 * ==========================================================================*/
(function (global) {
  'use strict';

  const CATEGORIES = [
    {
      id: 'disneysongs', name: 'Disney Songs', icon: '🎵',
      tiers: [
        [ // $400
          { q: 'Finish the Frozen song title: “Let It ___”',
            c: ['Go', 'Be', 'Snow', 'Rain'], a: 0,
            why: '“Let It Go” — the Oscar-winning anthem from Frozen (2013).' },
          { q: 'Finish The Little Mermaid title: “Under the ___”',
            c: ['Sea', 'Moon', 'Stars', 'Bridge'], a: 0,
            why: '“Under the Sea” — Sebastian’s big calypso number.' },
          { q: 'Which film features the song “A Whole New World”?',
            c: ['Aladdin', 'Hercules', 'Tarzan', 'Mulan'], a: 0,
            why: '“A Whole New World” is the magic-carpet duet from Aladdin (1992).' },
        ],
        [ // $800
          { q: 'Finish the Beauty and the Beast title: “Be Our ___”',
            c: ['Guest', 'Friend', 'Hero', 'King'], a: 0,
            why: '“Be Our Guest” — Lumière’s dinner spectacular.' },
          { q: 'Finish the Moana title: “How Far I’ll ___”',
            c: ['Go', 'Sail', 'Run', 'Fly'], a: 0,
            why: '“How Far I’ll Go” — Moana’s ocean-calling ballad.' },
          { q: 'Which film gave us the song “Hakuna Matata”?',
            c: ['The Lion King', 'The Jungle Book', 'Tarzan', 'Brother Bear'], a: 0,
            why: '“Hakuna Matata” — Timon and Pumbaa’s worry-free philosophy.' },
        ],
        [ // $1200
          { q: 'Finish The Lion King title: “Can You Feel the Love ___”',
            c: ['Tonight', 'Again', 'Forever', 'Somehow'], a: 0,
            why: '“Can You Feel the Love Tonight” won the 1995 Best Original Song Oscar.' },
          { q: 'Finish the Encanto title: “We Don’t Talk About ___”',
            c: ['Bruno', 'Mirabel', 'Abuela', 'Isabela'], a: 0,
            why: '“We Don’t Talk About Bruno” became Encanto’s breakout hit.' },
          { q: 'In Moana, the show-stopper “You’re Welcome” is sung by which character?',
            c: ['Maui', 'Moana', 'Tamatoa', 'Chief Tui'], a: 0,
            why: 'Maui (voiced by Dwayne Johnson) lists his own legendary deeds.' },
        ],
        [ // $1600
          { q: 'Which Disney song won the Academy Award for Best Original Song for the 2013 film year?',
            c: ['Let It Go', 'How Far I’ll Go', 'Remember Me', 'Into the Unknown'], a: 0,
            why: '“Let It Go” (Frozen) took the 2014 ceremony’s Best Original Song.' },
          { q: 'The song “Remember Me” is the emotional centerpiece of which Pixar film?',
            c: ['Coco', 'Soul', 'Onward', 'Up'], a: 0,
            why: '“Remember Me” threads through Coco and won Best Original Song (2018).' },
          { q: 'Songwriters Robert Lopez and Kristen Anderson-Lopez wrote the songs for which pair of Disney hits?',
            c: ['Frozen and Coco', 'Moana and Encanto', 'Tangled and Brave', 'Aladdin and Mulan'], a: 0,
            why: 'The Lopez duo wrote Frozen’s and Coco’s Oscar-winning songs.' },
        ],
      ],
    },
    {
      id: 'disney', name: 'Disney Trivia', icon: '🏰',
      tiers: [
        [
          { q: 'What kind of animal is Dumbo?',
            c: ['Horse', 'Elephant', 'Mouse', 'Dog'], a: 1,
            why: 'A young circus elephant whose enormous ears let him fly.' },
          { q: "Mickey Mouse's dog is named…",
            c: ['Goofy', 'Pluto', 'Rex', 'Max'], a: 1,
            why: 'Pluto is Mickey’s pet; Goofy is a separate character.' },
          { q: 'Which Disney film features a snowman named Olaf?',
            c: ['Frozen', 'Tangled', 'Moana', 'Encanto'], a: 0,
            why: 'Olaf is the warm-hug-loving snowman from Frozen (2013).' },
        ],
        [
          { q: 'Which princess has a pet tiger named Rajah?',
            c: ['Jasmine', 'Mulan', 'Belle', 'Ariel'], a: 0,
            why: 'Princess Jasmine, in Aladdin (1992).' },
          { q: 'In Encanto, the family’s magical house is called…',
            c: ['Casita', 'El Castillo', 'La Villa', 'Casa Grande'], a: 0,
            why: 'The sentient house “Casita” protects the Madrigals.' },
          { q: 'Moana sails to restore the heart of which island goddess?',
            c: ['Te Fiti', 'Te Kā', 'Tala', 'Sina'], a: 0,
            why: 'Te Fiti, whose stolen heart Maui must help return.' },
        ],
        [
          { q: 'In what year did Disneyland open in California?',
            c: ['1955', '1966', '1971', '1949'], a: 0,
            why: 'July 17, 1955 in Anaheim. Walt Disney World followed in 1971.' },
          { q: 'Which was Walt Disney’s first sound cartoon starring Mickey Mouse?',
            c: ['Steamboat Willie', 'Plane Crazy', 'Fantasia', 'The Band Concert'], a: 0,
            why: 'Steamboat Willie (1928) launched Mickey with synchronized sound.' },
          { q: 'What is the castle at the center of Florida’s Magic Kingdom?',
            c: ['Sleeping Beauty Castle', 'Cinderella Castle', 'Beast’s Castle', 'Elsa’s Ice Palace'], a: 1,
            why: 'Cinderella Castle is Florida’s icon; California has Sleeping Beauty Castle.' },
        ],
        [
          { q: 'Which Disney theme park resort opened FIRST outside the United States?',
            c: ['Tokyo Disneyland', 'Disneyland Paris', 'Hong Kong Disneyland', 'Shanghai Disneyland'], a: 0,
            why: 'Tokyo Disneyland opened in 1983, the first Disney park abroad.' },
          { q: 'Walt Disney personally won a record how many competitive Academy Awards?',
            c: ['12', '22', '5', '30'], a: 1,
            why: 'Walt Disney holds the record with 22 competitive Oscars.' },
          { q: 'What was the company’s original 1923 name?',
            c: ['Disney Brothers Cartoon Studio', 'Walt Disney Productions', 'Buena Vista', 'Mickey Mouse Inc.'], a: 0,
            why: 'It began as the Disney Brothers Cartoon Studio, Walt and Roy.' },
        ],
      ],
    },
    {
      id: 'movies', name: 'At the Movies', icon: '🎬',
      tiers: [
        [
          { q: "Which film gave us the line 'To infinity and beyond!'?",
            c: ['Toy Story', 'Cars', 'Up', 'WALL·E'], a: 0,
            why: "Buzz Lightyear's catchphrase, from Toy Story (1995)." },
          { q: 'In Finding Nemo, what kind of fish is Nemo?',
            c: ['Blue tang', 'Clownfish', 'Angelfish', 'Guppy'], a: 1,
            why: 'Nemo and Marlin are clownfish; Dory is the blue tang.' },
          { q: 'Which Pixar film is set largely inside a girl’s mind?',
            c: ['Soul', 'Inside Out', 'Coco', 'Onward'], a: 1,
            why: 'Inside Out (2015) personifies Riley’s emotions.' },
        ],
        [
          { q: "In WALL·E, the sleek robot WALL·E falls for is named…",
            c: ['EVA', 'EVE', 'M-O', 'AUTO'], a: 1,
            why: 'EVE — the Extraterrestrial Vegetation Evaluator.' },
          { q: 'Which film features a rat who wants to be a chef in Paris?',
            c: ['Ratatouille', 'A Bug’s Life', 'Flushed Away', 'The Aristocats'], a: 0,
            why: 'Ratatouille (2007) — Remy the rat cooks through Linguini.' },
          { q: 'In Coco, the Land of the Dead is reached during which holiday?',
            c: ['Halloween', 'Día de los Muertos', 'Cinco de Mayo', 'New Year'], a: 1,
            why: 'Coco is built around Día de los Muertos.' },
        ],
        [
          { q: 'Which was the first feature-length fully computer-animated film?',
            c: ['Shrek', 'Toy Story', 'Antz', 'A Bug’s Life'], a: 1,
            why: 'Toy Story (1995) was the first fully CGI animated feature.' },
          { q: 'Up opens with a near-wordless montage of whose life together?',
            c: ['Carl and Ellie', 'Russell and Carl', 'Miguel and Héctor', 'Woody and Buzz'], a: 0,
            why: 'Carl and Ellie’s marriage — a celebrated sequence.' },
          { q: 'In Ratatouille, the feared food critic is named…',
            c: ['Anton Ego', 'Auguste Gusteau', 'Skinner', 'Linguini'], a: 0,
            why: 'Anton Ego, whose review is disarmed by a humble ratatouille.' },
        ],
        [
          { q: 'Which was Pixar’s SECOND feature film, released in 1998?',
            c: ['A Bug’s Life', 'Toy Story 2', 'Monsters, Inc.', 'Finding Nemo'], a: 0,
            why: 'A Bug’s Life (1998) followed Toy Story (1995).' },
          { q: 'The 1937 film that was the first full-length cel-animated feature is…',
            c: ['Pinocchio', 'Snow White and the Seven Dwarfs', 'Fantasia', 'Bambi'], a: 1,
            why: 'Snow White and the Seven Dwarfs (1937).' },
          { q: 'Which Pixar film features the emotions Joy, Sadness, Fear, Anger and Disgust?',
            c: ['Inside Out', 'Soul', 'Turning Red', 'Luca'], a: 0,
            why: 'The five core emotions steer Riley in Inside Out.' },
        ],
      ],
    },
    {
      id: 'costopt', name: 'Cost Optimization', icon: '💸',
      tiers: [
        [
          { q: 'Migrating an EC2 workload from Intel to Graviton typically saves about…',
            c: ['~5%', '~20%', '~45%', '~70%'], a: 1,
            why: 'Intel → Graviton ≈ 20%. Usually a rebuild-and-redeploy.' },
          { q: 'The cheapest resource to run is…',
            c: ['A Spot instance', 'A Graviton instance', 'One you turned off', 'A Reserved Instance'], a: 2,
            why: 'An idle resource you switch off costs nothing. Delete beats discount.' },
          { q: 'Which EBS change is a near-free ~20%-per-GB win?',
            c: ['gp2 → gp3', 'gp3 → io2', 'Add more IOPS', 'Bigger volume'], a: 0,
            why: 'gp3 is ~20% cheaper per GB and lets you set IOPS/throughput independently.' },
        ],
        [
          { q: 'Moving cold S3 Standard data to Intelligent-Tiering saves roughly…',
            c: ['~5%', '~40–68%', '~90%+', 'It costs more'], a: 1,
            why: 'Intelligent-Tiering saves ~40–68% on infrequently-accessed data.' },
          { q: 'RDS Graviton2 delivers roughly what price/performance improvement?',
            c: ['~12%', '~25%', '~52%', '~80%'], a: 2,
            why: 'RDS Graviton2 is ~52% better price/performance.' },
          { q: 'The safest place to START right-sizing is…',
            c: ['Production', 'Non-prod / dev', 'The database tier', 'Disaster recovery'], a: 1,
            why: 'Non-prod is over-provisioned and forgiving — prove the right-size there first.' },
        ],
        [
          { q: 'A 3-year Compute Savings Plan on steady usage can save up to…',
            c: ['~10%', '~30%', '~66%', '~90%'], a: 2,
            why: 'Up to ~66% for a 3-year all-upfront Compute Savings Plan.' },
          { q: 'Lambda on ARM/Graviton2 improves price-performance by about…',
            c: ['~5%', '~34%', '~60%', '~90%'], a: 1,
            why: 'Up to ~34% better price-performance — often just a flag flip.' },
          { q: 'To cut a replicated DynamoDB table burning KMS cost, the lever is…',
            c: ['Smaller items', 'An AWS-owned key instead of a CMK', 'More partitions', 'On-demand mode'], a: 1,
            why: 'A per-request CMK call is billed each time; an AWS-owned key removes it.' },
        ],
        [
          { q: 'Migrating from AMD to Graviton (a common Mariner case) saves roughly…',
            c: ['~10%', '~30%', '~50%', '~70%'], a: 0,
            why: 'AMD → Graviton is ~10% theoretical; on shared infra 5–10% is realistic.' },
          { q: 'The deepest committed-use discount comes from a…',
            c: ['1-yr no-upfront Savings Plan', '3-yr all-upfront Savings Plan', 'On-demand plan', 'Spot request'], a: 1,
            why: '3-year all-upfront trades the most flexibility for the biggest discount.' },
          { q: 'S3 Intelligent-Tiering’s Archive Instant Access tier suits data that is…',
            c: ['Read constantly', 'Rarely accessed but needs millisecond retrieval', 'Never accessed again', 'Streamed live'], a: 1,
            why: 'It’s cheap cold storage that still returns in milliseconds when you do need it.' },
        ],
      ],
    },
    {
      id: 'cloud', name: 'Cloud Engineering', icon: '☁️',
      tiers: [
        [
          { q: 'Which EC2 instance family is actually Graviton (ARM)?',
            c: ['m5a', 'r5', 'm6g', 'c5'], a: 2,
            why: 'A trailing "g" means Graviton (m6g, c7g, t4g).' },
          { q: 'What does "EC2" stand for?',
            c: ['Elastic Compute Cloud', 'Enterprise Container Cluster', 'Elastic Cache Cloud', 'Edge Compute Center'], a: 0,
            why: 'Elastic Compute Cloud — AWS’s core virtual-server service.' },
          { q: 'An "auto-scaling group" exists mainly to…',
            c: ['Encrypt traffic', 'Add/remove capacity with demand', 'Store backups', 'Route DNS'], a: 1,
            why: 'It grows and shrinks the fleet to match load.' },
        ],
        [
          { q: 'An idle NAT gateway with no traffic still bills you for…',
            c: ['Nothing', 'An hourly charge (plus per-GB when used)', 'Only data processed', 'Only DNS lookups'], a: 1,
            why: 'NAT gateways bill an hourly rate whether or not a byte flows.' },
          { q: 'How do you confirm an ALB is genuinely idle before deleting it?',
            c: ['Check the monthly bill', 'Check RequestCount / active targets', 'Restart it', 'Ask the team'], a: 1,
            why: 'Zero RequestCount and no healthy targets over a real window is the evidence.' },
          { q: 'The main advantage of EBS gp3 over gp2, beyond ~20% lower cost, is…',
            c: ['Faster snapshots', 'IOPS/throughput configured independently', 'Free encryption', 'No minimum size'], a: 1,
            why: 'gp3 decouples IOPS/throughput from capacity.' },
        ],
        [
          { q: 'Which CUR usage type flags an EKS cluster on an EOL Kubernetes version?',
            c: ['BoxUsage', 'ExtendedSupport', 'DataTransfer', 'EBS:VolumeUsage'], a: 1,
            why: 'An "ExtendedSupport" line is AWS surcharging an end-of-life version.' },
          { q: 'A NodeUsage line vanishes for a resource. Before calling it decommissioned…',
            c: ['Celebrate', 'Check for an engine upgrade on the same resource_id', 'Delete the tag', 'Open a ticket'], a: 1,
            why: 'A dropped line can mean an upgrade, not a shutdown.' },
          { q: 'Which EFS throughput mode generally avoids overpaying?',
            c: ['Provisioned', 'Elastic', 'Bursting only', 'Max I/O always'], a: 1,
            why: 'Elastic scales throughput to demand — no fixed ceiling to pay for.' },
        ],
        [
          { q: 'A gateway VPC endpoint for S3 or DynamoDB costs…',
            c: ['Per hour', 'Per GB', 'Nothing — it is free', 'Per request'], a: 2,
            why: 'Gateway endpoints are free; interface (PrivateLink) endpoints are the ones that bill.' },
          { q: 'The Fargate launch type trades EC2 for…',
            c: ['Lower cost always', 'Per-task pricing and no servers to manage', 'Weaker security', 'Less scaling'], a: 1,
            why: 'Fargate bills per task/vCPU-memory and removes node management — convenience over raw cost.' },
          { q: 'A big lever on cross-AZ data-transfer cost is…',
            c: ['Bigger instances', 'Keeping chatty traffic within one AZ', 'More AZs', 'Disabling autoscaling'], a: 1,
            why: 'Cross-AZ traffic bills per GB each way; AZ-aware placement cuts it.' },
        ],
      ],
    },
    {
      id: 'tokenomics', name: 'Tokenomics', icon: '🪙',
      tiers: [
        [
          { q: 'In the CostBot Arcade, banking 10,000 tokens does what?',
            c: ['Buys a skin', 'Ships another CostBot product', 'Resets your score', 'Nothing yet'], a: 1,
            why: 'Every 10,000 banked tokens ships another product. Banking is one-way.' },
          { q: 'One "token" in LLM billing is roughly…',
            c: ['One word', 'About 4 characters', 'One sentence', 'One byte'], a: 1,
            why: 'A token averages ~4 characters of English.' },
          { q: 'LLM APIs bill you for…',
            c: ['Only output tokens', 'Both input and output tokens', 'Only input tokens', 'Wall-clock time'], a: 1,
            why: 'You pay for the prompt (input) AND the completion (output), at different rates.' },
        ],
        [
          { q: "For Disney's Bedrock usage, which Anthropic model tier carries the deepest discount off list?",
            c: ['Haiku', 'Sonnet', 'Opus', 'They are identical'], a: 2,
            why: 'Opus lands the deepest enterprise discount off list.' },
          { q: 'The single biggest lever on a chatbot’s token bill is usually…',
            c: ['Model temperature', 'Prompt / context length', 'The font', 'Region'], a: 1,
            why: 'Every request re-sends the context; trimming it cuts input tokens each call.' },
          { q: 'Prompt caching cuts cost by…',
            c: ['Skipping the model', 'Reusing a cached prefix at a reduced rate', 'Batching users', 'Lowering quality'], a: 1,
            why: 'A cached prefix is billed at a fraction of the normal input rate.' },
        ],
        [
          { q: 'The cheapest way to run a large one-off batch of prompts is usually…',
            c: ['Real-time API', 'The Batch API (async, discounted)', 'One request at a time', 'A bigger model'], a: 1,
            why: 'Async batch endpoints trade latency for a standing discount.' },
          { q: 'A "mixture of experts" model can be cheaper to serve because…',
            c: ['It is smaller on disk', 'Only some parameters activate per token', 'It skips attention', 'It never caches'], a: 1,
            why: 'MoE routes each token through a subset of experts.' },
          { q: 'A 200k-token context window means…',
            c: ['200k users', '~200k tokens of prompt+history fit at once', '200k requests', '200k tokens/second'], a: 1,
            why: 'The window is how much text the model can consider in one call.' },
        ],
        [
          { q: 'Speculative decoding speeds generation by…',
            c: ['Skipping tokens', 'Drafting with a small model, verifying with the big one', 'Caching prompts', 'Lowering precision'], a: 1,
            why: 'A cheap draft model proposes tokens the large model then verifies in bulk.' },
          { q: 'Quantizing a model to lower precision mainly reduces…',
            c: ['Accuracy only', 'Memory and compute per token', 'Network egress', 'Prompt storage'], a: 1,
            why: 'Fewer bits per weight means less memory and cheaper math per token.' },
          { q: 'Anthropic’s enterprise discount seen on Disney’s Bedrock billing has been measured at exactly…',
            c: ['12%', '15%', '30%', '50%'], a: 0,
            why: 'Billing shows a consistent 12.000% off list outside one credit window; 15% appears nowhere.' },
        ],
      ],
    },
    {
      id: 'finops', name: 'FinOps Engineering', icon: '📊',
      tiers: [
        [
          { q: 'What does "CUR" stand for?',
            c: ['Cloud Usage Report', 'Cost & Usage Report', 'Compute Utilization Rate', 'Cloud Unit Rate'], a: 1,
            why: 'The Cost & Usage Report is AWS’s line-item billing export.' },
          { q: 'What unlocks cost allocation beyond a tidy bill?',
            c: ['Bigger instances', 'Consistent resource tagging', 'More accounts', 'Turning off the CUR'], a: 1,
            why: 'Tags split a shared bill by team, service, or environment.' },
          { q: 'The best first question when a bill spikes is…',
            c: ['Who do we blame?', 'What changed, and when?', 'Can we get a refund?', 'Should we switch clouds?'], a: 1,
            why: 'Anomalies have a cause with a timestamp — find the change first.' },
        ],
        [
          { q: '"Showback" differs from "chargeback" because showback…',
            c: ["Bills the team's budget", 'Only reports the cost, no invoice', 'Refunds waste', 'Hides the cost'], a: 1,
            why: 'Showback reports; chargeback moves the money.' },
          { q: 'Cost-allocation-tag activation is…',
            c: ['Retroactive to all history', 'Only effective going forward', 'Automatic', 'Free only'], a: 1,
            why: 'Activating a tag does not backfill old line items.' },
          { q: 'Amortized cost differs from unblended cost by…',
            c: ['Ignoring discounts', 'Spreading upfront commitments over their term', 'Adding tax', 'Rounding up'], a: 1,
            why: 'Amortized smears a prepaid SP/RI across the months it covers.' },
        ],
        [
          { q: "The FinOps Foundation's three lifecycle phases are Inform, Optimize, and…",
            c: ['Operate', 'Automate', 'Eliminate', 'Report'], a: 0,
            why: 'Inform → Optimize → Operate.' },
          { q: 'A team’s Kinesis bill is >50% "ConsumerHour". That signals…',
            c: ['Too little data', 'Many enhanced fan-out consumers', 'A tagging bug', 'A Spot interruption'], a: 1,
            why: 'ConsumerHour is enhanced fan-out — consumers, not throughput, drive it.' },
          { q: 'To isolate one EMR cluster’s EC2 and storage cost, you join on…',
            c: ['Account name', 'The cluster id / resource id', 'Region', 'The team tag alone'], a: 1,
            why: 'Resource id ties every underlying line item back to that cluster.' },
        ],
        [
          { q: 'FinOps "unit economics" expresses cost per…',
            c: ['Account', 'Unit of business value (e.g. per order)', 'Region', 'Instance'], a: 1,
            why: 'Tying spend to a business unit is what makes cost a product metric.' },
          { q: 'For a commitment, "utilization" measures…',
            c: ['% of eligible usage covered', '% of the commitment actually used', 'Total spend', 'Savings realized'], a: 1,
            why: 'Utilization = how much of what you committed to actually got used (coverage is the other side).' },
          { q: '"Blended" cost in an AWS Organization averages rates across…',
            c: ['Regions', 'Linked accounts sharing a discount', 'Time', 'Services'], a: 1,
            why: 'Blended rates spread a shared RI/SP benefit evenly across linked accounts.' },
        ],
      ],
    },
    {
      id: 'spotcommit', name: 'Spot & Commitments', icon: '🎲',
      tiers: [
        [
          { q: 'Spot instances are discounted by up to roughly…',
            c: ['~30%', '~50%', '~70%', '~90%'], a: 3,
            why: 'Spot runs up to ~90% off — the trade is AWS can reclaim it anytime.' },
          { q: 'The best Spot candidate among these is…',
            c: ['The primary prod database', 'A CI/CD build fleet', 'A stateful session store', 'The payment gateway'], a: 1,
            why: 'Spot suits fault-tolerant work — CI/CD, batch, ML.' },
          { q: 'A Reserved Instance fits when usage is…',
            c: ['Spiky', 'Stable over the next 12 months', 'Weekend-only', 'Already on Spot'], a: 1,
            why: 'Commitments reward predictability.' },
        ],
        [
          { q: 'The main risk you design around when adopting Spot is…',
            c: ['Slower CPUs', 'Higher transfer fees', 'Instances reclaimed mid-run', 'No CloudWatch metrics'], a: 2,
            why: 'Capacity can be interrupted anytime — make workloads restart-safe.' },
          { q: 'A 1-year Reserved Instance on stable EC2 usage yields roughly…',
            c: ['~10%', '~30%', '~65%', '~90%'], a: 1,
            why: 'About 30% for 1-year RIs on stable usage.' },
          { q: 'Reserved capacity on DynamoDB yields roughly…',
            c: ['~15%', '~30%', '~50%', '~75%'], a: 2,
            why: 'DynamoDB reserved capacity runs ~50% for stable 12-month usage.' },
        ],
        [
          { q: 'A Compute Savings Plan is more flexible than an EC2 Instance SP because it…',
            c: ['Costs less always', 'Floats across family, size, region and Fargate/Lambda', 'Never expires', 'Needs no commitment'], a: 1,
            why: 'Compute SPs float widely; EC2 Instance SPs lock to a family in a region.' },
          { q: 'Over-committing coverage against falling demand means you…',
            c: ['Save more', 'Pay for capacity you no longer use', 'Get a refund', 'Auto-downgrade'], a: 1,
            why: 'A commitment is a floor you pay regardless — unused portion is waste.' },
          { q: 'Since AWS’s late-2024 cut, which DynamoDB mode is often cheaper, especially for global tables?',
            c: ['Provisioned', 'On-demand', 'Identical', 'Neither — use RDS'], a: 1,
            why: 'The Nov-2024 cut made on-demand frequently the better default.' },
        ],
        [
          { q: 'A Spot Instance interruption notice gives you about…',
            c: ['2 minutes', '10 minutes', '1 hour', 'No notice'], a: 0,
            why: 'AWS sends a two-minute warning before reclaiming Spot capacity.' },
          { q: 'AWS applies a Savings Plan to your usage in order of…',
            c: ['Random', 'Highest discount percentage first', 'Lowest first', 'Alphabetical'], a: 1,
            why: 'It maximizes your benefit by covering the highest-savings usage first.' },
          { q: 'An EC2 Instance Savings Plan locks you to…',
            c: ['Any instance anywhere', 'A specific instance family in a region', 'Only Spot', 'A single instance id'], a: 1,
            why: 'It commits to a family+region — cheaper than Compute SPs, but rigid.' },
        ],
      ],
    },
    {
      id: 'storage', name: 'Storage & Data', icon: '🗄️',
      tiers: [
        [
          { q: 'You delete an orphaned EBS volume whose instance is long gone. You save…',
            c: ['0% — snapshots still bill', '~30%', '~50%', '100% of that volume cost'], a: 3,
            why: 'Deletion is a 100% saving. Snapshot first if you need a backup.' },
          { q: 'S3 charges you for storage in…',
            c: ['Requests only', 'GB stored per month', 'Number of buckets', 'Number of prefixes'], a: 1,
            why: 'Core S3 cost is GB-months, plus request and retrieval charges.' },
          { q: 'Which S3 class is for data you rarely, if ever, retrieve?',
            c: ['S3 Standard', 'S3 Glacier Deep Archive', 'S3 Standard-IA', 'S3 Express One Zone'], a: 1,
            why: 'Glacier Deep Archive is the cheapest, for cold data you can wait hours for.' },
        ],
        [
          { q: 'Incomplete multipart uploads sitting in a bucket are…',
            c: ['Free', 'Billed as storage until removed', 'Auto-deleted in 24h', 'Only billed on retrieval'], a: 1,
            why: 'Orphaned parts accrue storage cost — a lifecycle rule should abort them.' },
          { q: 'Which S3 lifecycle transition tends to save the MOST?',
            c: ['Standard → Standard-IA (~40%)', 'Standard-IA → Glacier IR (~68%)', 'Glacier → Deep Archive (~73%)', 'All ~10%'], a: 2,
            why: 'Roughly: Standard→IA 40%, IA→Glacier IR 68%, Glacier→Deep Archive 73%.' },
          { q: 'For EMR scratch storage, which fits best?',
            c: ['io2', 'gp3', 'st1 HDD', 'Instance store where possible'], a: 3,
            why: 'Ephemeral scratch belongs on cheap local/instance store, not premium SSD.' },
        ],
        [
          { q: 'Moving a Kinesis stream Provisioned → On-Demand eliminates which worry?',
            c: ['Data durability', 'Guessing shard count', 'Encryption', 'Ordering'], a: 1,
            why: 'On-demand removes shard-capacity planning.' },
          { q: 'Under KODA (Kinesis On-Demand Advantage), you are billed a per-region…',
            c: ['Maximum', 'Minimum baseline', 'Flat $0', 'Per-consumer fee'], a: 1,
            why: 'KODA carries a per-region minimum — small streams can pay more.' },
          { q: 'A high-EFO Kinesis stream can cost MORE under KODA because…',
            c: ['EFO is free normally', 'Enhanced fan-out consumers are billed differently', 'It disables sharding', 'Of data transfer'], a: 1,
            why: 'KODA changes how enhanced-fan-out consumer cost lands.' },
        ],
        [
          { q: 'S3 Glacier Deep Archive’s minimum storage duration is…',
            c: ['30 days', '90 days', '180 days', 'None'], a: 2,
            why: 'Delete before 180 days and you still pay to the minimum — fine for true cold data.' },
          { q: 'EBS snapshot cost is based on…',
            c: ['Provisioned volume size', 'Changed blocks stored incrementally', 'Number of snapshots', 'IOPS'], a: 1,
            why: 'Snapshots are incremental — you pay for changed blocks, not full copies.' },
          { q: 'A high-volume DynamoDB table burning KMS cost points at…',
            c: ['Too few partitions', 'A customer-managed key called per request', 'On-demand mode', 'Global tables'], a: 1,
            why: 'Each encrypt/decrypt against a CMK is billed; an AWS-owned key drops that charge.' },
        ],
      ],
    },
    {
      id: 'billofmonth', name: 'Bill of the Month', icon: '🧾',
      tiers: [
        [
          { q: 'The famously scariest line on a cloud bill is often…',
            c: ['Compute', 'Data transfer / egress', 'Storage', 'Support'], a: 1,
            why: 'Egress creeps up quietly and is hard to attribute.' },
          { q: '"Rightsizing" means…',
            c: ['Buying the biggest instance', 'Matching capacity to real demand', 'Deleting everything', 'Only autoscaling'], a: 1,
            why: 'Fitting the instance to the workload — no slack, no starvation.' },
          { q: 'A "zombie" resource is one that is…',
            c: ['Encrypted', 'Running but unused, still billing', 'On Spot', 'Tagged wrong'], a: 1,
            why: 'Orphaned volumes, idle load balancers — alive on the bill, dead in use.' },
        ],
        [
          { q: 'A sudden 3× jump in one service overnight is best called a…',
            c: ['Feature', 'Cost anomaly', 'Discount', 'Rounding error'], a: 1,
            why: 'A sharp unexplained spike is an anomaly — investigate the change.' },
          { q: 'Cross-AZ traffic within one region is…',
            c: ['Always free', 'Billed per GB each way', 'Only billed inbound', 'Billed monthly flat'], a: 1,
            why: 'Data crossing AZs is charged per GB — chatty services add up.' },
          { q: 'CloudWatch Logs cost that is "pure profit" to cut is usually…',
            c: ['Deleting all logs', 'Setting retention on never-read logs', 'Turning off metrics', 'Lowering the region'], a: 1,
            why: 'Logs nobody queries, kept forever, bill forever.' },
        ],
        [
          { q: 'Finout, in the Cost Management stack, is the platform for…',
            c: ['Deploying apps', 'Cost visibility / allocation', 'CI/CD', 'Incident paging'], a: 1,
            why: 'Finout is where spend gets sliced and attributed.' },
          { q: 'The Disney rate on some AWS usage (e.g. NAT) vs AWS list can be…',
            c: ['Higher', 'About the same', '~48% lower', 'Exactly list'], a: 2,
            why: 'Negotiated rates put Disney (engineering) cost well below list on some usage.' },
          { q: 'When Cost Explorer and the CUR disagree, attribute by…',
            c: ['The team tag', 'line_item_resource_id', 'Account name', 'Region'], a: 1,
            why: 'Resource id ties cost to the actual thing; tag activation is not retroactive.' },
        ],
        [
          { q: 'Data transfer OUT to the internet is billed; data transfer IN is generally…',
            c: ['More expensive', 'Free', 'Per request', 'Taxed'], a: 1,
            why: 'Inbound transfer is free; it’s the egress that bites.' },
          { q: 'A saving that is "realized" (not just "potential") means…',
            c: ['A recommendation exists', 'A change was made and the bill actually dropped', 'A forecast', 'A discount offer'], a: 1,
            why: 'Potential is a suggestion; realized is money that left the invoice.' },
          { q: 'Korean K-ISMS audit logging adds cost mainly through which service?',
            c: ['CloudFront', 'CloudTrail', 'CloudWatch Synthetics', 'Config'], a: 1,
            why: 'K-ISMS drives heavy CloudTrail logging — ~$40K/month, variable on usage.' },
        ],
      ],
    },
  ];

  // Final Forecast: harder, mixed. One is chosen from three offered categories.
  const FINALS = [
    { cat: 'Fiscal Calendar', q: "Disney's fiscal year begins in which month?",
      c: ['January', 'July', 'October', 'April'], a: 2,
      why: "Disney's fiscal year starts in October — Q1 is Oct–Dec." },
    { cat: 'Cloud Deep Cut', q: 'AWS Graviton processors are built on which CPU architecture?',
      c: ['x86', 'ARM', 'RISC-V', 'MIPS'], a: 1,
      why: 'Graviton is ARM-based (Neoverse cores).' },
    { cat: 'The Fine Print', q: 'Which purchasing model can AWS reclaim with about two minutes’ warning?',
      c: ['Reserved Instances', 'On-Demand', 'Spot', 'Savings Plans'], a: 2,
      why: 'Spot trades a ~90% discount for a two-minute interruption notice.' },
    { cat: 'Reliability Math', q: 'A "three nines" SLA (99.9%) permits roughly how much downtime per year?',
      c: ['~8.7 hours', '~52 minutes', '~5 minutes', '~3.6 days'], a: 0,
      why: '99.9% of a year is ~8.76 hours. Each extra nine cuts it ~10×.' },
    { cat: 'Optimization', q: 'RDS Graviton2 delivers roughly what price/performance improvement over Intel?',
      c: ['~12%', '~25%', '~52%', '~80%'], a: 2,
      why: 'RDS Graviton2 is ~52% better price/performance.' },
    { cat: 'Tokenomics', q: 'Roughly how many tokens is 750 words of English?',
      c: ['~100', '~1,000', '~10,000', '~100,000'], a: 1,
      why: 'About 4 characters per token → ~750 words ≈ 1,000 tokens.' },
    { cat: 'Studio History', q: 'Which 1937 film was the first full-length cel-animated feature?',
      c: ['Pinocchio', 'Snow White and the Seven Dwarfs', 'Fantasia', 'Bambi'], a: 1,
      why: 'Snow White and the Seven Dwarfs (1937).' },
    { cat: 'Disney Songs', q: '“Let It Go” won Best Original Song for which studio’s film?',
      c: ['Pixar', 'Walt Disney Animation', 'DreamWorks', 'Illumination'], a: 1,
      why: 'Frozen is Walt Disney Animation Studios; “Let It Go” won the 2014 Oscar.' },
  ];

  global.BoardMeetingContent = { CATEGORIES, FINALS };
})(typeof window !== 'undefined' ? window : globalThis);
